"""Sandbox shadow runner — G2 Genesis DNA.

Executes staged code inside an isolated shadow-trading environment using the
Chronos synthetic regime generator (G7) to achieve statistical confidence
before production deployment. Per AGENTS.md §3 (G2), the *machinery* that
orchestrates the shadow run is Genesis DNA; the specific candidate policy
(alpha heuristics) is injected by the Evolution Sub-Agent (S2) and is never
hardcoded here.

Per AGENTS.md §2 (G2): "The machinery that reads code, runs theorem provers,
sandboxes, and merges patches." This module is that machinery — a thin
orchestration layer over the simulation engine.
"""
import time
from collections.abc import Callable
from dataclasses import dataclass

from simulation.synthetic_gen import SyntheticRegimeGenerator


@dataclass
class ShadowSimulationConfig:
    """
    Data-driven shadow-trading parameters.

    Per AGENTS.md §7 ("DNS/schema over code"), all thresholds and durations
    are data — the Evolution Sub-Agent may re-parameterize via config
    without code changes. The specific market regimes are generated by
    SyntheticRegimeGenerator (G7); this config only controls the simulation
    envelope.
    """

    simulated_years: int = 1
    confidence_threshold: float = 0.999
    start_equity: float = 1_000_000.0
    max_acceptable_drawdown: float = 0.99
    volatility: float = 0.01
    price_points_per_year: int = 365


@dataclass
class ShadowSimulationResult:
    """
    Structured outcome of a shadow sandbox run.

    The Evolution Sub-Agent consumes this to decide whether to promote
    a patch to the Constitution's Kani + production pipeline.
    """

    passed: bool
    final_equity: float
    worst_drawdown: float
    elapsed_seconds: float
    years_simulated: int
    error: str | None = None


class SandboxShadowRunner:
    """
    Executes staged code inside an isolated shadow-trading environment
    to achieve the configured statistical confidence before production deployment.

    The runner uses SyntheticRegimeGenerator (G7) to produce high-entropy
    market regimes (FLASH_CRASH, HYPERINFLATION_LOOP, etc.) and replays
    them against the candidate policy. Survival (equity > 0) and drawdown
    (below threshold) determine pass/fail.
    """

    def __init__(self, patch_id: str):
        self.patch_id = patch_id
        self._generator = SyntheticRegimeGenerator()

    def execute_shadow_simulation(
        self,
        config: ShadowSimulationConfig | None = None,
        candidate_policy: Callable | None = None,
    ) -> ShadowSimulationResult:
        """
        Run the candidate code through a shadow-trading simulation.

        Args:
            config: Simulation envelope parameters. Defaults to a 1-year
                run at 1M equity with a 99% drawdown ceiling (survival gate;
                the Constitution's I1 threshold of 15% is enforced separately
                at the risk-kernel level). The sandbox verifies the candidate
                code survives extreme regime shocks without crashing or
                exhausting equity.
            candidate_policy: The policy being tested (injected by the
                Evolution Sub-Agent). Signature: ``(equity: float) ->
                None``. If None, a no-op hold policy is used.

        Returns:
            ShadowSimulationResult with pass/fail + metrics.
        """
        cfg = config or ShadowSimulationConfig()
        start = time.perf_counter()

        if candidate_policy is not None:
            policy = candidate_policy
        else:
            policy = lambda equity: None

        try:
            final_equity, worst_drawdown, years_done = self._run_simulation(
                cfg, policy
            )
        except Exception as exc:  # noqa: BLE001 - sandbox must not crash the host
            elapsed = time.perf_counter() - start
            return ShadowSimulationResult(
                passed=False,
                final_equity=cfg.start_equity,
                worst_drawdown=0.0,
                elapsed_seconds=elapsed,
                years_simulated=0,
                error=str(exc),
            )

        elapsed = time.perf_counter() - start
        passed = final_equity > 0.0 and worst_drawdown <= cfg.max_acceptable_drawdown

        return ShadowSimulationResult(
            passed=passed,
            final_equity=final_equity,
            worst_drawdown=worst_drawdown,
            elapsed_seconds=elapsed,
            years_simulated=years_done,
        )

    def _run_simulation(
        self,
        cfg: ShadowSimulationConfig,
        policy: Callable,
    ) -> tuple[float, float, int]:
        """
        Core simulation loop using SyntheticRegimeGenerator (G7).

        Replays synthetic price paths through the candidate policy and
        tracks equity/drawdown metrics. This is the *mechanism* —
        the policy is injected, not hardcoded.
        """
        equity = cfg.start_equity
        peak = equity
        worst_drawdown = 0.0

        for year in range(cfg.simulated_years):
            _prices, curve = self._generator.generate_price_path(
                start_price=100.0,
                points=cfg.price_points_per_year,
                volatility=cfg.volatility,
            )

            if not curve:
                continue

            baseline = curve[0]
            if baseline <= 0.0:
                baseline = 1.0

            for tick in curve:
                equity *= tick / baseline
                if equity <= 0.0:
                    equity = 0.0
                    return (equity, worst_drawdown, year)
                peak = max(peak, equity)
                drawdown = (peak - equity) / peak
                worst_drawdown = max(worst_drawdown, drawdown)
                policy(equity)

        return (equity, worst_drawdown, cfg.simulated_years)
