"""AssetConversionOracle — the narrow, Genesis-stable interface the dead-man
daemon consumes (Phase 14.3). Concrete venue/custodian connectors are
system-written (S7); the interface and deterministic simulation are ours."""

from __future__ import annotations

import hashlib
from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum

from pydantic import BaseModel, Field


class ConversionStatus(str, Enum):
    SUBMITTED = "SUBMITTED"
    SETTLED = "SETTLED"
    FAILED = "FAILED"


class ConversionQuote(BaseModel):
    asset_in: str = Field(min_length=1)
    asset_out: str = Field(min_length=1)
    quantity_in: float = Field(gt=0.0)
    est_quantity_out: float = Field(gt=0.0)
    quote_ref: str
    indicative: bool = True


class ConversionOrder(BaseModel):
    order_id: str
    quote_ref: str
    asset_in: str
    asset_out: str
    quantity_in: float
    status: ConversionStatus


class AssetConversionOracle(ABC):
    @abstractmethod
    def quote(self, asset_in: str, asset_out: str, quantity_in: float) -> ConversionQuote:
        """Firm (or indicative) quote; the daemon stores quote_ref before acting."""

    @abstractmethod
    def submit_conversion_request(self, quote: ConversionQuote) -> ConversionOrder:
        """Submit only against a known quote_ref; never a blind order."""

    @abstractmethod
    def get_conversion_status(self, order_id: str) -> ConversionOrder:
        """Return the current status of a conversion order by ID."""


@dataclass
class _SimulationBook:
    orders: dict[str, ConversionOrder] | None = None


class SimulationOracle(AssetConversionOracle):
    """Deterministic oracle for sandbox/tests: 1:1 conversion minus a fixed fee."""

    def __init__(self, fee_bps: int = 0) -> None:
        self._fee_bps = fee_bps
        self._orders: dict[str, ConversionOrder] = {}

    def quote(self, asset_in: str, asset_out: str, quantity_in: float) -> ConversionQuote:
        if quantity_in <= 0:
            raise ValueError("quantity_in must be positive")
        est = quantity_in * (1.0 - self._fee_bps / 10_000.0)
        ref = hashlib.sha256(
            f"{asset_in}:{asset_out}:{quantity_in}:{self._fee_bps}".encode()
        ).hexdigest()[:16]
        return ConversionQuote(
            asset_in=asset_in,
            asset_out=asset_out,
            quantity_in=quantity_in,
            est_quantity_out=est,
            quote_ref=ref,
        )

    def submit_conversion_request(self, quote: ConversionQuote) -> ConversionOrder:
        order = ConversionOrder(
            order_id=f"sim-{quote.quote_ref}",
            quote_ref=quote.quote_ref,
            asset_in=quote.asset_in,
            asset_out=quote.asset_out,
            quantity_in=quote.quantity_in,
            status=ConversionStatus.SUBMITTED,
        )
        self._orders[order.order_id] = order
        return order

    def get_conversion_status(self, order_id: str) -> ConversionOrder:
        if order_id not in self._orders:
            raise KeyError(f"unknown conversion order: {order_id}")
        return self._orders[order_id]

    def settle(self, order_id: str) -> ConversionOrder:
        order = self.get_conversion_status(order_id)
        assert order.status is ConversionStatus.SUBMITTED
        order.status = ConversionStatus.SETTLED
        return order


class ConfigDrivenOracle(AssetConversionOracle):
    """Data-driven stub that routes to a configured inner oracle.

    The inner implementation arrives via schema config (`oracle:` name). Any
    concrete rail (custodian, venue settlement) is generated by the system (S7);
    this class only proves the wiring path exists.
    """

    def __init__(self, inner: AssetConversionOracle, label: str = "config") -> None:
        self._inner = inner
        self.label = label

    def quote(self, asset_in: str, asset_out: str, quantity_in: float) -> ConversionQuote:
        return self._inner.quote(asset_in, asset_out, quantity_in)

    def submit_conversion_request(self, quote: ConversionQuote) -> ConversionOrder:
        return self._inner.submit_conversion_request(quote)

    def get_conversion_status(self, order_id: str) -> ConversionOrder:
        return self._inner.get_conversion_status(order_id)


def oracle_factory(name: str) -> AssetConversionOracle:
    """Map a config `oracle:` name to an implementation. Unknown names fail
    closed — the daemon must never improvise a connector."""
    known = {
        "simulation_oracle": lambda: SimulationOracle(),
    }
    if name not in known:
        raise ValueError(f"unknown oracle provider: {name!r} (fail-closed)")
    return known[name]()